name: Tests
on:
  pull_request:
  schedule:
    - cron: "0 23 * * *"

jobs:
  tests:
    name: Tests
    
    runs-on: ubuntu-latest
    strategy:
        matrix:
          go: ["1.16", "1.15", "1.14", "1.13"]
    env:
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.3

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Format
        run: test -z $(gofmt -l .)

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Tests
        timeout-minutes: 10
        run: go test -v ./...
        
      - name: Flush db
        if: always()
        run: go run ./cmd/flush